import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os

# Set Page Config
st.set_page_config(
    page_title="Loan Approval Prediction System",
    page_icon="💸",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Premium Custom CSS
st.markdown("""
<style>
    /* Styling headers and fonts */
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap');
    
    html, body, [class*="css"] {
        font-family: 'Outfit', sans-serif;
    }
    
    h1, h2, h3 {
        font-weight: 800 !important;
        color: #1A365D;
    }
    
    /* Premium card background styling */
    .stApp {
        background-color: #F7FAFC;
    }
    
    /* Button design */
    .stButton>button {
        background: linear-gradient(135deg, #3182CE 0%, #2B6CB0 100%);
        color: white;
        border: None;
        padding: 12px 30px;
        border-radius: 8px;
        font-weight: 600;
        font-size: 16px;
        width: 100%;
        box-shadow: 0 4px 6px -1px rgba(49, 130, 206, 0.4);
        transition: all 0.3s ease;
    }
    .stButton>button:hover {
        background: linear-gradient(135deg, #2B6CB0 0%, #2B6CB0 100%);
        transform: translateY(-2px);
        box-shadow: 0 6px 12px -2px rgba(49, 130, 206, 0.5);
    }
    
    /* Status indicators */
    .approved-container {
        padding: 24px;
        border-radius: 12px;
        background-color: #EBF8FF;
        border-left: 6px solid #3182CE;
        margin-top: 20px;
    }
    .denied-container {
        padding: 24px;
        border-radius: 12px;
        background-color: #FFF5F5;
        border-left: 6px solid #E53E3E;
        margin-top: 20px;
    }
</style>
""", unsafe_allow_html=True)

# Load Pipeline
@st.cache_resource
def load_pipeline():
    base_dir = os.path.dirname(__file__)
    pipeline_path = os.path.join(base_dir, 'loan_model_pipeline.joblib')
    return joblib.load(pipeline_path)

try:
    pipeline = load_pipeline()
    model = pipeline['model']
    imputer_num = pipeline['imputer_num']
    imputer_cat = pipeline['imputer_cat']
    le_edu = pipeline['le_edu']
    ohe = pipeline['ohe']
    scaler = pipeline['scaler']
    feature_names = pipeline['feature_names']
    num_cols = pipeline['num_cols']
    cat_cols = pipeline['cat_cols']
    ohe_cols = pipeline['ohe_cols']
    pipeline_loaded = True
except Exception as e:
    st.error("Error loading model pipeline. Please make sure 'loan_model_pipeline.joblib' is generated by running 'train_model.py'.")
    pipeline_loaded = False

# Sidebar Info
with st.sidebar:
    st.image("https://img.icons8.com/isometric/100/loan.png", width=80)
    st.title("Loan System")
    st.markdown("This intelligent system evaluates customer creditworthiness using a trained **Logistic Regression** model.")
    st.info("Fill in the applicant and financial details to run a real-time prediction.")
    st.divider()
    st.caption("Developed as part of ML Loan System Project")

# Main Title
st.title("💸 Loan Approval Predictor")
st.markdown("Fill out the forms below to determine the loan approval status and confidence score.")

if pipeline_loaded:
    # Setup inputs in columns
    col1, col2 = st.columns(2, gap="large")

    with col1:
        st.subheader("👤 Applicant Profile")
        gender = st.selectbox("Gender", options=["Female", "Male"])
        age = st.slider("Age", min_value=18, max_value=100, value=35)
        marital_status = st.selectbox("Marital Status", options=["Married", "Single"])
        dependents = st.number_input("Number of Dependents", min_value=0, max_value=10, value=0, step=1)
        education = st.selectbox("Education Level", options=["Graduate", "Not Graduate"])
        employment_status = st.selectbox("Employment Status", options=["Salaried", "Self-employed", "Contract", "Unemployed"])
        employer_category = st.selectbox("Employer Category", options=["Private", "Government", "MNC", "Business", "Unemployed"])
        property_area = st.selectbox("Property Area", options=["Urban", "Semiurban", "Rural"])

    with col2:
        st.subheader("💰 Financial & Loan details")
        app_income = st.number_input("Applicant Income ($)", min_value=0.0, value=5000.0, step=500.0)
        coapp_income = st.number_input("Coapplicant Income ($)", min_value=0.0, value=0.0, step=500.0)
        credit_score = st.slider("Credit Score", min_value=300, max_value=850, value=650)
        dti_ratio = st.slider("Debt-to-Income (DTI) Ratio", min_value=0.0, max_value=1.0, value=0.3, step=0.01)
        savings = st.number_input("Savings ($)", min_value=0.0, value=1000.0, step=500.0)
        collateral = st.number_input("Collateral Value ($)", min_value=0.0, value=5000.0, step=1000.0)
        loan_amount = st.number_input("Loan Amount Requested ($)", min_value=0.0, value=10000.0, step=1000.0)
        loan_term = st.selectbox("Loan Term (Months)", options=[12, 24, 36, 48, 60, 72, 84, 120])
        loan_purpose = st.selectbox("Loan Purpose", options=["Home", "Car", "Education", "Personal", "Business"])
        existing_loans = st.number_input("Number of Existing Loans", min_value=0, max_value=10, value=0, step=1)

    st.divider()

    # Predict Button
    if st.button("Check Approval Status"):
        # 1. Construct DataFrame from inputs
        input_data = {
            "Applicant_Income": float(app_income),
            "Coapplicant_Income": float(coapp_income),
            "Employment_Status": employment_status,
            "Age": float(age),
            "Marital_Status": marital_status,
            "Dependents": float(dependents),
            "Credit_Score": float(credit_score),
            "Existing_Loans": float(existing_loans),
            "DTI_Ratio": float(dti_ratio),
            "Savings": float(savings),
            "Collateral_Value": float(collateral),
            "Loan_Amount": float(loan_amount),
            "Loan_Term": float(loan_term),
            "Loan_Purpose": loan_purpose,
            "Property_Area": property_area,
            "Education_Level": education,
            "Gender": gender,
            "Employer_Category": employer_category
        }
        
        df_input = pd.DataFrame([input_data])

        # 2. Imputation
        df_input[num_cols] = imputer_num.transform(df_input[num_cols])
        df_input[cat_cols] = imputer_cat.transform(df_input[cat_cols])

        # 3. Label Encoding (binary categoricals)
        df_input["Education_Level"] = le_edu.transform(df_input["Education_Level"])

        # 4. One-Hot Encoding
        encoded = ohe.transform(df_input[ohe_cols])
        encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(ohe_cols), index=df_input.index)
        df_input = pd.concat([df_input.drop(columns=ohe_cols), encoded_df], axis=1)

        # 5. Feature Engineering (Squaring key features)
        df_input["Credit_Score_sq"] = df_input["Credit_Score"] ** 2
        df_input["DTI_Ratio_sq"] = df_input["DTI_Ratio"] ** 2

        # 6. Align features in exactly the expected order
        X_input = df_input[feature_names]

        # 7. Scale
        X_scaled = scaler.transform(X_input)

        # 8. Predict
        prediction = model.predict(X_scaled)[0]
        probabilities = model.predict_proba(X_scaled)[0]

        # 9. Output UI based on prediction
        # Success and Error calls in Streamlit are secure against HTML/JS injection by default
        if prediction == 1:
            st.markdown("""
            <div class="approved-container">
                <h3>🎉 Loan Approved!</h3>
                <p>Congratulations! The applicant is predicted to be creditworthy.</p>
            </div>
            """, unsafe_allow_html=True)
            st.metric(label="Approval Probability", value=f"{probabilities[1]*100:.2f}%")
        else:
            st.markdown("""
            <div class="denied-container">
                <h3>⚠️ Loan Denied</h3>
                <p>We regret to inform you that the loan request has been rejected.</p>
            </div>
            """, unsafe_allow_html=True)
            st.metric(label="Rejection Probability", value=f"{probabilities[0]*100:.2f}%")
